config/routes.rb
Rails.application.routes.draw do
	root "static_pages#home"
	get 'static_pages/about'
	get 'static_pages/fee'	
	get 'static_pages/rights'		
	get "/static_pages/:page" => "statc_pages#show"  
  namespace :admin do
    resources :users, only: [:index]
    resources :articles 
    resources :types, only: [:new, :create, :edit, :update, :destroy]
    resources :brands, only: [:index, :edit, :update, :destroy] do
      resources :types, only: [:update]
    end
    get "/dashboard", to: "dashboards#index"
  end        
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
  	resources :articles, only: [:index, :show]				
   	resources :products, only: [:index, :show]	  	  		   	
    resources :articles, only: [:index, :show]  
    resources :products, only: [:index, :show] do
      member do 
        post :sendmail
      end
    end      
	end
	match "*.path", to: redirect("/#{I18n.default_locale}/%{path}"), :via => [:get, :post]
  match "", to: redirect("/#{I18n.default_locale}"), :via => [:get, :post]
  match "*path" => redirect("/"), via: :get
	get "search(/:search)", to: "searches#index", as: :search
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
  	mount_uploader :image, ImageUploader	

	scope :load_article, -> {
		where(order: :desc)
	}

	scope :time_created, -> {
		where (DateTime.now - created_at.to_date)
	}
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_action :get_article, only: [:show, :edit, :update, :destroy]
  def index
  	@articles = Article.paginate(:page => params[:page], :per_page => 5).order(created_at: :desc)
  end

  def show;end

  def new
  	@article = Article.new
  end

  def create
 	@article = Article.new article_params
 	@article.created_at = Time.now
    if @article.save
      flash[:success] = t("create")
      redirect_to new_admin_article_path
    else
      flash[:error] = t("error")
      redirect_to new_admin_article_path
    end
  end

  def edit;end

  def update
    if @article.update_attributes article_params
      flash[:success] = t("updated")
      redirect_to admin_articles_path
    else
      flash[:danger] = t("error")
      render :edit
    end
  end

  def destroy
  	if @article.present?
      @article.destroy
    end
    if @article.destroy
      flash[:success] = t("deleted")
      redirect_to request.referrer || @articles
    else
      flash[:error] = t("error")
      redirect_to @articles
    end
  end

  private
  def get_article
    redirect_to admin_dashboard_path unless @article = Article.find_by(id: params[:id])
  end

  def article_params
  	params.require(:article).permit(:title, :text, :image, :description)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :get_article, only: :show
  
  def index
  	@articles = Article.distinct.paginate(:page => params[:page], :per_page => 9).order(created_at: :desc)
  end

  def show;end

  private
  def get_article
    redirect_to root_url unless @article = Article.find_by(id: params[:id])
  end

end

app/views/admin/articles/edit.html.erb
<div id="page-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<h2 class="page-header title"><%= t ".edit_article" %></h2>
			</div>
		</div>
		<%= form_for [:admin, @article], :html => {:multipart => true} do |f| %>
		<%= render 'shared/error_messages',object: f.object %>
		<div class="field">
			<%= f.label :title, t(".title") %>:
			<div>
				<%= f.text_area :title, class: "form-control" %>
			</div>
		</div>
		<div class="field">
			<%= f.label :title, t(".text") %>:
			<%= f.text_area :text, class: "tinymce" %>
			<%= tinymce %>
		</div>
		<div class="field">
			<%= f.label :title, t(".description") %>:
			<div>		
				<%= f.text_area :description, class: "form-control" %>
			</div>
		</div>
		<div class="field">
			<%= f.label :image, t(".image") %>:
			<%= f.file_field :image %>
		</div>
		<i style="float: right"><%= link_to t("shared.ack"), :back, class: "btn btn-warning" %></i>
		<%= f.submit t("shared.edit"), class: "btn btn-success pull-right" %>		
		<% end %>
	</div>
</div>

app/views/admin/articles/index.html.erb
<div id="page-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<h2 class="page-header title"><%= t ".article_list" %></h2>
			</div>
		</div>
		<table class="table table-bordered mt-5" >
			<thead>
				<tr class="bold">
					<th><%= t "shared.article.title" %></th>
					<th><%= t "shared.article.description" %></th>
					<th><%= t "shared.article.date" %></th>
					<th><%= t ".action" %></th>
					<th><%= t ".action" %></th>
				</tr>
			</thead>
			<tbody>
				<% @articles.each do |article| %>
				<tr style="text-align: center;">
					<td><%= article.title %></td>
					<td><%= truncate(article.description, length: 100) %></td>					
					<td><%= article.created_at.strftime("%d/%m/%Y") %></td>
					<td><%= link_to t(".info"), admin_article_path(article), class: "btn btn-info" %></td>
					<td class="text-center">
						<%= link_to t(".delete"), admin_article_path(article),
						method: :delete, data: {confirm: t("shared.message.you_sure")},
						class: "btn btn-danger" %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<div><%= will_paginate @articles, :previous_label => t("shared.previous"), :next_label => t('shared.next') %></div>
	</div>
</div>

app/views/admin/articles/new.html.erb
<div id="page-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<h2 class="page-header title"><%= t ".new_article" %></h2>
			</div>
		</div>
		<%= form_for [:admin, @article], :html => {:multipart => true} do |f| %>
		<%= render 'shared/error_messages',object: f.object %>
		<div class="field">
			<%= f.label :title, t(".atitle") %>:
			<div>
				<%= f.text_area :title, placeholder: t(".title"), class: "form-control" %>
			</div>
		</div>
		<div class="field">
			<%= f.label :title, t(".atext") %>:
			<%= f.text_area :text, placeholder: t(".text"), class: "tinymce" %>
			<%= tinymce %>
		</div>
		<div class="field">
			<%= f.label :title, t(".adescription") %>:
			<div>		
				<%= f.text_area :description, placeholder: t(".description"), class: "form-control" %>
			</div>
		</div>
		<div class="field">
			<%= f.label :image, t(".aimage") %>:
			<%= f.file_field :image %>
		</div>
		<i style="float: right"><%= link_to t("shared.back"), :back, class: "btn btn-warning" %></i>
		<%= f.submit t("shared.create"), class: "btn btn-primary pull-right" %>
		<% end %>
	</div>
</div>

app/views/admin/articles/show.html.erb
<div id="page-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<h2 class="page-header title"><%= t ".article" %></h2>
			</div>
		</div>
		<h3 class="field text-center">
		<%= @article.title.upcase %>
		</h3>
		<div class="field text-center">
			<b><%= @article.description %></b>
		</div>
		<div class="field text-center">
			<%= @article.text.html_safe if !@article.text.nil? %>
		</div>
		<div>
			<i style="float: right"><%= link_to t("shared.back"), :back, class: "btn btn-warning" %></i>
			<%= link_to t("shared.edit"), edit_admin_article_path(@article), class: "btn btn-success pull-right" %>			
		</div>
	</div>
</div>