config/routes.rb
Rails.application.routes.draw do
	root "static_pages#home"
	get 'static_pages/about'
	get 'static_pages/fee'	
	get 'static_pages/rights'		
	get "/static_pages/:page" => "statc_pages#show"  
  namespace :admin do
    resources :users, only: [:index]
    resources :articles 
    resources :types, only: [:new, :create, :edit, :update, :destroy]
    resources :brands, only: [:index, :edit, :update, :destroy] do
      resources :types, only: [:update]
    end
    get "/dashboard", to: "dashboards#index"
  end        
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
  	resources :articles, only: [:index, :show]				
   	resources :products, only: [:index, :show]	  	  		   	
    resources :articles, only: [:index, :show]  
    resources :products, only: [:index, :show] do
      member do 
        post :sendmail
      end
    end      
	end
	match "*.path", to: redirect("/#{I18n.default_locale}/%{path}"), :via => [:get, :post]
  match "", to: redirect("/#{I18n.default_locale}"), :via => [:get, :post]
  match "*path" => redirect("/"), via: :get
	get "search(/:search)", to: "searches#index", as: :search
end

app/models/brand.rb
class Brand < ApplicationRecord
	belongs_to :product
	has_many :types	
	accepts_nested_attributes_for :types
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < Admin::ApplicationController
  before_action :get_brand, only: [:edit, :update, :destroy]
  def index
    @brands = Brand.paginate(page: params[:page], per_page: 5).order(name: :asc)
  end

  def edit
    @types = Type.all.order(name: :asc)
  end

  def update
    if @brand.update_attributes automobile_params
    Type.where(id: params[:type_ids]).update_all(brand_id: @brand.id, updated_at: Time.now)
      flash[:success] = t("updated")
      redirect_to admin_brands_path
    else
      flash[:danger] = t("error")
      render :edit
    end    
  end

  def destroy
    if @brand.present?
      @brand.destroy
    end
    if @brand.destroy
      flash[:success] = t("deleted")
      redirect_to request.referrer || @brands
    else
      flash[:error] = t("error")
      redirect_to @brands
    end
  end

  private
  def get_brand
    redirect_to admin_dashboard_path unless @brand = Brand.find_by(id: params[:id])
  end

  def brand_params
    params.require(:brand).permit(:name)
  end

  def automobile_params
    params.require(:brand).permit(:name, :brand_id)    
  end  
end

app/views/admin/brands/edit.html.erb
<div id="page-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<h2 class="page-header title"><%= t ".edit_brand" %></h2>
			</div>
		</div>
		<%= form_for [:admin, @brand], :html => {:multipart => true} do |f| %>
		<%= render 'shared/error_messages',object: f.object %>
		<div class="row">
			<div class="col-md-6">
				<%= f.label :name, t(".name") %>:
				<div>
					<%= f.text_area :name, placeholder: t(".name"), class: "form-control" %>
				</div>
			</div>
		</div>
		<div>
			<i style="float: right"><%= link_to t("shared.back"), :back, class: "btn btn-warning" %></i>		
			<%= f.submit t("shared.edit"), class: "btn btn-success pull-right" %>			
		</div>
		<% end %>
	</div>
</div>

app/views/admin/brands/index.html.erb
<div id="page-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<h2 class="page-header title"><%= t ".brand_list" %></h2>
			</div>
		</div>
		<table class="table table-bordered mt-5" >
			<thead>
				<tr class="bold">
					<th><%= t ".name" %></th>
					<th><%= t ".type" %></th>					
					<th><%= t ".action" %></th>					
					<th><%= t ".action" %></th>
				</tr>
			</thead>
			<tbody>
				<% @brands.each do |brand| %>
				<tr style="text-align: center;">
					<td><%= brand.name.html_safe %></td>					
					<td>
						<% brand.types.each do |type| %>
							<%= link_to type.name, edit_admin_type_path(type) %>   |
						<% end %>
					</td>										
					<td class="text-center">
						<%= link_to t("shared.edit"), edit_admin_brand_path(brand), class: "btn btn-success" %>
					</td>
					<td class="text-center">
						<%= link_to t(".delete"), admin_brand_path(brand),
						method: :delete, data: {confirm: t("shared.message.you_sure")},
						class: "btn btn-danger" %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<div><%= will_paginate @brands, :previous_label => t("shared.previous"), :next_label => t('shared.next') %></div>
	</div>
</div>

app/views/admin/brands/new.html.erb
<div id="page-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<h2 class="page-header title"><%= t ".new_brand" %></h2>
			</div>
		</div>
		<%= form_for [:admin, @brand], :html => {:multipart => true} do |f| %>
		<%= render 'shared/error_messages',object: f.object %>
		<div class="field">
			<%= f.text_area :name, placeholder: t(".name"), class: "form-control" %>
		</div>
		<%= f.submit t("shared.create"), class: "btn btn-primary" %>
		<i style="float: right"><%= link_to t('shared.back'), :back, class: "btn btn-warning" %></i>
		<% end %>
	</div>
</div>