config/routes.rb
Rails.application.routes.draw do
	root "static_pages#home"
	get 'static_pages/about'
	get 'static_pages/fee'	
	get 'static_pages/rights'		
	get "/static_pages/:page" => "statc_pages#show"  
  namespace :admin do
    resources :users, only: [:index]
    resources :articles 
    resources :types, only: [:new, :create, :edit, :update, :destroy]
    resources :brands, only: [:index, :edit, :update, :destroy] do
      resources :types, only: [:update]
    end
    get "/dashboard", to: "dashboards#index"
  end        
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
  	resources :articles, only: [:index, :show]				
   	resources :products, only: [:index, :show]	  	  		   	
    resources :articles, only: [:index, :show]  
    resources :products, only: [:index, :show] do
      member do 
        post :sendmail
      end
    end      
	end
	match "*.path", to: redirect("/#{I18n.default_locale}/%{path}"), :via => [:get, :post]
  match "", to: redirect("/#{I18n.default_locale}"), :via => [:get, :post]
  match "*path" => redirect("/"), via: :get
	get "search(/:search)", to: "searches#index", as: :search
end

app/views/layouts/admin/_admin_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <ul class="nav navbar-nav navbar-left navbar-top-links">
    <li>
      <%= link_to root_url do %>
      <i class="fa fa-home"></i>
      <%= t "layouts.header.home" %>
      <% end %>
    </li>
  </ul>
  <ul class="nav navbar-right navbar-top-links">
    <li class="dropdown navbar-inverse">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-flag fa-fw"></i><%= I18n.locale %> <b class="caret"></b>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <li><%= link_to t("layouts.header.english"), locale:"en" %></li>
        <li class="divider"></li>
        <li><%= link_to t("layouts.header.vietnam"), locale:"vi" %></li>
      </ul>
    </li>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-gear fa-fw"></i> <%= t ".settings" %> <b class="caret"></b>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <li><%= link_to edit_user_registration_path(locale: I18n.locale) do %>
          <i class="fa fa-user fa-fw"></i>
          <%= t ".user_profile" %>
          <% end %>
        </li>
        <li class="divider"></li>
        <li><%= link_to destroy_user_session_path(locale: I18n.locale), method: :delete do %>
          <i class="fa fa-sign-out fa-fw"></i>
          <%= t "layouts.header.logout" %>
          <% end %>
        </li>
      </ul>
    </li>
  </ul>
  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li><%= link_to admin_dashboard_path(locale: I18n.locale) do %>
          <i class="active fa fa-dashboard fa-fw"></i>
          <%= t ".dashboard" %>
          <% end %>
        </li>
        <li>
          <a href="#"><i class="fa fa-table fa-fw"></i> <%= t ".table" %>
            <span class="fa arrow"></span></a>
          <ul class="nav nav-second-level">
            <li>
              <%= link_to t("shared.users"), admin_users_path(locale: I18n.locale) %>
            </li>
            <li>
              <%= link_to t("shared.articles"), admin_articles_path(locale: I18n.locale) %>
            </li>
            <li>
              <%= link_to t("shared.brands"), admin_brands_path(locale: I18n.locale) %>
            </li>
          </ul>
        </li>
        <li>
          <a href="#"><i class="fa fa-plus-circle fa-fw"></i> <%= t ".addition" %>
            <span class="fa arrow"></span></a>
          <ul class="nav nav-second-level">
            <li><%= link_to t("shared.articles"), new_admin_article_path(locale: I18n.locale) %></li>
            <li><%= link_to t("shared.types"), new_admin_type_path(locale: I18n.locale) %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>