config/routes.rb
Rails.application.routes.draw do
	root "static_pages#home"
	get 'static_pages/about'
	get 'static_pages/fee'	
	get 'static_pages/rights'		
	get "/static_pages/:page" => "statc_pages#show"  
  namespace :admin do
    resources :users, only: [:index]
    resources :articles 
    resources :types, only: [:new, :create, :edit, :update, :destroy]
    resources :brands, only: [:index, :edit, :update, :destroy] do
      resources :types, only: [:update]
    end
    get "/dashboard", to: "dashboards#index"
  end        
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
  	resources :articles, only: [:index, :show]				
   	resources :products, only: [:index, :show]	  	  		   	
    resources :articles, only: [:index, :show]  
    resources :products, only: [:index, :show] do
      member do 
        post :sendmail
      end
    end      
	end
	match "*.path", to: redirect("/#{I18n.default_locale}/%{path}"), :via => [:get, :post]
  match "", to: redirect("/#{I18n.default_locale}"), :via => [:get, :post]
  match "*path" => redirect("/"), via: :get
	get "search(/:search)", to: "searches#index", as: :search
end

app/views/shared/_article.html.erb
<div class="row">
  <% @articles.each do |article| %>
  <div class="col-xs-6 col-md-4">
    <div class="article-item">
      <%= link_to article_path(article, locale: I18n.locale), class: "panel-title" do %>
      <h2>
        <%= article.title %>
      </h2>
      <% end %>
      <div class="summary">
        <div class="thumbnail-article">
          <%= image_tag article.image_url(:thumb) if article.image? %>
        </div>
        <p class="content"><%= truncate(article.description, length: 300) %></p>
      </div>
      <%= link_to t("static_pages.home.more_detail"), article_path(article, locale: I18n.locale), class: "btn btn-primary go-to-detail" %>
    </div>
  </div>
  <% end %>
</div>
<section style="visibility: visible; float: right;">
  <div class="row">
    <div class="col-xs-12 text-center">
      <a>
        <h3 class="text-uppercase"><%= link_to t("shared.all_articles"), articles_path(locale: I18n.locale), class: "btn btn-primary" %></h3>
      </a>
    </div>
  </div>
</section>

app/views/shared/_banner_page.html.erb
<div class="banner-page">
  <div class="container">
    <h2 class="text-center"><b><%= title %></b></h2>
    <hr />
    <p class="desc-title"></p>
    <div class="breadcrumb" typeof="BreadcrumbList" vocab="http://schema.org/">
      <!-- Breadcrumb NavXT 6.4.0 -->
      <span property="itemListElement" typeof="ListItem">
        <% breadscrumb.each_with_index do |item, index| %>
        <a property="item" typeof="WebPage" title="Trang chủ" href="<%= item[:url] %>" class="home" itemprop="item" data-wpel-link="internal">
          <span property="name"><%= item[:title] %></span>
        </a>
        <% if index != breadscrumb.length - 1 %>
        <i class="fa fa-angle-double-right"></i>
        <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t".the_form_contains" %>
      <%= pluralize object.errors.count, t(".error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li class="bold"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_login.html.erb
<div class="modal fade" id="loginModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          &times;
        </button>
        <h4><%= t ".login" %></h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12">
            <%= form_for(:user, url: session_path(:user)) do |f| %>
            <form role="form">
              <div class="form-group">
                <%= f.label :email, t("devise.sessions.new.email") %>:<br />
                <%= f.text_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :password, t("devise.sessions.new.password") %>:<br />
                <%= f.password_field :password, autocomplete: "current-password", class: "form-control" %>
              </div>
              <div class="form-group checkbox">
                <%= f.check_box :remember_me %>
                <%= f.label :remember_me, t("devise.sessions.new.remember") %>
              </div>
              <%= f.submit t(".login"), class: "btn btn-success btn-block" %>
            </form>
            <% end %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="row">
          <div class="col-md-12">
            <span>
              <%= t ".not_a_member" %>
              <%= link_to t(".sign_up"), new_registration_path(:user), class: "modal-link" %>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_option1.html.erb
<div class="modal fade" id="optionModal1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="padding:35px 50px;">
        <button type="button" class="close" data-dismiss="modal">
        &times;
        </button>
        <h4>
        <span class="fa fa-lock"></span> <%= t "shared.options" %>
        </h4>
      </div>
      <div class="modal-body" style="padding:40px 50px;">
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex justify-content-between align-items-center info">
            <%= t "shared.option.description1" %>(<%= number_to_currency(Option.find_by_id(1).price, unit: "VNĐ", format: "%n %u", delimiter: ".", locale: :en, precision: 0) %>)
          </li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger pull-right" data-dismiss="modal">
          <span class="fa fa-times"></span> <%= t "shared.login.cancel" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_option2.html.erb
<div class="modal fade" id="optionModal2" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="padding:35px 50px;">
        <button type="button" class="close" data-dismiss="modal">
        &times;
        </button>
        <h4>
        <span class="fa fa-lock"></span> <%= t "shared.options" %>
        </h4>
      </div>
      <div class="modal-body" style="padding:40px 50px;">
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex justify-content-between align-items-center info">
            <%= t "shared.option.description2" %>(<%= number_to_currency(Option.find_by_id(2).price, unit: "VNĐ", format: "%n %u", delimiter: ".", locale: :en, precision: 0) %>)
          </li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger btn-default pull-right"
        data-dismiss="modal">
        <span class="fa fa-times"></span> <%= t "shared.login.cancel" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_option3.html.erb
<div class="modal fade" id="optionModal3" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="padding:35px 50px;">
        <button type="button" class="close" data-dismiss="modal">
        &times;
        </button>
        <h4>
        <span class="fa fa-lock"></span> <%= t "shared.options" %>
        </h4>
      </div>
      <div class="modal-body" style="padding:40px 50px;">
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex justify-content-between align-items-center info">
            <%= t "shared.option.description3" %>(<%= number_to_currency(Option.find_by_id(3).price, unit: "VNĐ", format: "%n %u", delimiter: ".", locale: :en, precision: 0) %>)
          </li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger btn-default pull-right"
        data-dismiss="modal">
        <span class="fa fa-times"></span> <%= t "shared.login.cancel" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_option4.html.erb
<div class="modal fade" id="optionModal4" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="padding:35px 50px;">
        <button type="button" class="close" data-dismiss="modal">
        &times;
        </button>
        <h4>
        <span class="fa fa-lock"></span> <%= t "shared.options" %>
        </h4>
      </div>
      <div class="modal-body" style="padding:40px 50px;">
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex justify-content-between align-items-center info">
            <%= t "shared.option.description4" %>(<%= number_to_currency(Option.find_by_id(4).price, unit: "VNĐ", format: "%n %u", delimiter: ".", locale: :en, precision: 0) %>)
          </li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger btn-default pull-right"
        data-dismiss="modal">
        <span class="fa fa-times"></span> <%= t "shared.login.cancel" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_option5.html.erb
<div class="modal fade" id="optionModal5" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="padding:35px 50px;">
        <button type="button" class="close" data-dismiss="modal">
        &times;
        </button>
        <h4>
        <span class="fa fa-lock"></span> <%= t "shared.options" %>
        </h4>
      </div>
      <div class="modal-body" style="padding:40px 50px;">
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex justify-content-between align-items-center info">
            <%= t "shared.option.description5" %>(<%= number_to_currency(Option.find_by_id(5).price, unit: "VNĐ", format: "%n %u", delimiter: ".", locale: :en, precision: 0) %>)
          </li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger btn-default pull-right"
        data-dismiss="modal">
        <span class="fa fa-times"></span> <%= t "shared.login.cancel" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_option6.html.erb
<div class="modal fade" id="optionModal6" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="padding:35px 50px;">
        <button type="button" class="close" data-dismiss="modal">
        &times;
        </button>
        <h4>
        <span class="fa fa-lock"></span> <%= t "shared.options" %>
        </h4>
      </div>
      <div class="modal-body" style="padding:40px 50px;">
        <ul class="list-group list-group-flush">        
          <li class="list-group-item d-flex justify-content-between align-items-center info">
            <%= t "shared.option.description6" %>(<%= number_to_currency(Option.find_by_id(6).price, unit: "VNĐ", format: "%n %u", delimiter: ".", locale: :en, precision: 0) %>)
          </li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger btn-default pull-right"
        data-dismiss="modal">
        <span class="fa fa-times"></span> <%= t "shared.login.cancel" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_option7.html.erb
<div class="modal fade" id="optionModal7" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="padding:35px 50px;">
        <button type="button" class="close" data-dismiss="modal">
        &times;
        </button>
        <h4>
        <span class="fa fa-lock"></span> <%= t "shared.options" %>
        </h4>
      </div>
      <div class="modal-body" style="padding:40px 50px;">
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex justify-content-between align-items-center info">
            <%= t "shared.option.description7" %>(<%= number_to_currency(Option.find_by_id(7).price, unit: "VNĐ", format: "%n %u", delimiter: ".", locale: :en, precision: 0) %>)
          </li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger btn-default pull-right"
        data-dismiss="modal">
        <span class="fa fa-times"></span> <%= t "shared.login.cancel" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_option8.html.erb
<div class="modal fade" id="optionModal8" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="padding:35px 50px;">
        <button type="button" class="close" data-dismiss="modal">
        &times;
        </button>
        <h4>
        <span class="fa fa-lock"></span> <%= t "shared.options" %>
        </h4>
      </div>
      <div class="modal-body" style="padding:40px 50px;">
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex justify-content-between align-items-center info">
            <%= t "shared.option.description8" %>(<%= number_to_currency(Option.find_by_id(8).price, unit: "VNĐ", format: "%n %u", delimiter: ".", locale: :en, precision: 0) %>)
          </li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger btn-default pull-right"
        data-dismiss="modal">
        <span class="fa fa-times"></span> <%= t "shared.login.cancel" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<% if items.blank? %>
  <li>
    <%= link_to search_path(params[:search]),
      class: "btn btn-default btn-block" do %>
      <%= "No results for #{params[:search]}" %>
    <% end %>
  </li>
<% else %>
  <div class="scrollable-menu">
    <% items.each do |item| %>
      <%= render "products/search_item", product: item %>
    <% end %>
  </div>
  <li class="divider"></li>
  <li>
    <%= link_to search_path(params[:search]),
      class: "btn btn-default btn-block" do %>
      <%= "See more #{items.size} for #{params[:search]}" %>
    <% end %>
  </li>
<% end %>

app/views/shared/_sign_up.html.erb
<div class="modal fade" id="signupModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="padding:35px 50px;">
        <button type="button" class="close" data-dismiss="modal">
          &times;
        </button>
        <h4>
          <span class="fa fa-lock"></span> <%= t ".sign_up" %>
        </h4>
      </div>
      <div class="modal-body" style="padding:40px 50px;">
        <%= form_for(:user, url: registration_path(:user)) do |f| %>
        <form role="form">
          <div class="form-group">
            <span class="fa fa-user"></span>
            <%= f.label :name, t("devise.sessions.new.name") %>:<br />
            <%= f.text_field :name, autofocus: true, autocomplete: "name",
            class: "form-control" %>
          </div>
          <div class="form-group">
            <span class="fa fa-envelope"></span>
            <%= f.label :email %>:<br />
            <%= f.email_field :email, autocomplete: "email",
            class: "form-control" %>
          </div>
          <div class="form-group">
            <span class="fa fa-phone"></span>
            <%= f.label :phone, t(".phone") %>:<br />
            <%= f.text_field :phone, autocomplete: "phone",
            class: "form-control" %>
          </div>
          <div class="form-group">
            <span class="fa fa-eye"></span>
            <%= f.label :password, t("devise.sessions.new.password") %>:<br />
            <%= f.password_field :password, autocomplete: "off",
            class: "form-control" %>
          </div>
          <div class="form-group">
            <span class="fa fa-eye"></span>
            <%= f.label :password_confirmation,
            t(".password_confirm") %>:<br />
            <%= f.password_field :password_confirmation, autocomplete: "off",
            class: "form-control" %>
          </div>
          <%= f.submit t(".sign_up"),
          class: "btn btn-success btn-block" %>
        </form>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal">
          <span class="fa fa-times"></span> <%= t "shared.login.cancel" %>
        </button>
      </div>
    </div>
  </div>
</div>